--- Create a warehouse called ACME_WH, make it size XS. 
USE ROLE SYSADMIN;
CREATE WAREHOUSE ADU_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    WAREHOUSE_TYPe = 'STANDARD'
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE;
USE WAREHOUSE ADU_WH;
