-- Create FLOWER_DETAILS Table
CREATE OR REPLACE TABLE GARDEN_PLANTS.FLOWERS.FLOWERS_DETAILS
(
    PLANT_NAME VARCHAR(25),
	ROOT_DEPTH_CODE VARCHAR(1)
);

-- Query the created table
SELECT * 
FROM GARDEN_PLANTS.FLOWERS.FLOWERS_DETAILS;

-- Create FRUIT_DETAILS Table
CREATE OR REPLACE TABLE GARDEN_PLANTS.FRUITS.FRUIT_DETAILS
(
    PLANT_NAME VARCHAR(25),
	ROOT_DEPTH_CODE VARCHAR(1)
);

-- Query the created table
SELECT * 
FROM GARDEN_PLANTS.FRUITS.FRUIT_DETAILS;
