-- Use the AccountAdmin role for the following commands
USE ROLE ACCOUNTADMIN;

-- Create an API Integration
CREATE or REPLACE API INTEGRATION DORA_API_INTEGRATION
API_PROVIDER = AWS_API_GATEWAY
API_AWS_ROLE_ARN = 'arn:aws:iam::321463406630:role/snowflakeLearnerAssumedRole'
ENABLED = TRUE
API_ALLOWED_PREFIXES = ('https://awy6hshxy4.execute-api.us-west-2.amazonaws.com/dev/edu_dora');

-- Create the GRADER Function
CREATE OR REPLACE EXTERNAL FUNCTION UTIL_DB.PUBLIC.GRADER(
    STEP VARCHAR,
    PASSED BOOLEAN,
    ACTUAL INTEGER,
    EXPECTED INTEGER,
    DESCRIPTION VARCHAR)
RETURNS VARIANT
API_INTEGRATION = DORA_API_INTEGRATION
CONTEXT_HEADERS = (CURRENT_TIMESTAMP, CURRENT_ACCOUNT, CURRENT_STATEMENT, CURRENT_ACCOUNT_NAME)
AS 'https://awy6hshxy4.execute-api.us-west-2.amazonaws.com/dev/edu_dora/grader';

-- Check Function
SHOW FUNCTIONS LIKE '%GRADER%' IN ACCOUNT;

-- Test the Function
SELECT UTIL_DB.PUBLIC.GRADER(
    STEP,
    (ACTUAL = EXPECTED),
    ACTUAL,
    EXPECTED,
    DESCRIPTION
) AS GRADED_RESULTS FROM
(
    SELECT 'DORA_IS_WORKING' AS STEP,
    (SELECT 123) AS ACTUAL,
    123 AS EXPECTED,
    'Dora is working!' AS DESCRIPTION
);