--- What Countries are Included in the HISTORY_DAY View
--
SELECT 
    DISTINCT COUNTRY
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;
    
--
SELECT 
    COUNT(DISTINCT COUNTRY)
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;

--
SELECT 
    COUNTRY
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE
    COUNTRY = 'DE';



--- What Postal Codes Are Available from the Detroit Area
--
SELECT 
    DISTINCT POSTAL_CODE
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE
    COUNTRY = 'US'
    AND
    POSTAL_CODE LIKE '481%'
    OR
    POSTAL_CODE LIKE '482%';



--- Convert Your Postal Code Query to a View
--
CREATE DATABASE MARKETING;
CREATE SCHEMA MARKETING.MAILERS;
CREATE VIEW MARKETING.MAILERS.DETROIT_ZIPS
AS
SELECT 
    DISTINCT POSTAL_CODE
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE
    COUNTRY = 'US'
    AND 
    LEFT(POSTAL_CODE,3) IN ('481','482');

--
SELECT 
    * 
FROM 
    MARKETING.MAILERS.DETROIT_ZIPS;



--- How Can I Filter the Data and How Much Data Can I Remove With a Filter
-- 736117
SELECT
    COUNT(*)
FROM
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;

-- 6579
SELECT 
    COUNT(*)
FROM 
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY HD
JOIN
    MARKETING.MAILERS.DETROIT_ZIPS DZ
ON
    HD.POSTAL_CODE = DZ.POSTAL_CODE;



--- What's the Data Range on this Data Set
-- 
SELECT
    MIN(DATE_VALID_STD),
    MAX(DATE_VALID_STD)
FROM
    WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY HD
JOIN 
    MARKETING.MAILERS.DETROIT_ZIPS DZ
ON
    HD.POSTAL_CODE = DZ.POSTAL_CODE;

--
SELECT
    MIN(DATE_VALID_STD),
    MAX(DATE_VALID_STD)
FROM
    WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY FD
JOIN 
    MARKETING.MAILERS.DETROIT_ZIPS DZ
ON
    FD.POSTAL_CODE = DZ.POSTAL_CODE;



--- Can the Data Tell Me Which Day in the Next 2 Weeks Would Be Best for a Sale
--
SELECT
    FD.DATE_VALID_STD,
    AVG(FD.AVG_CLOUD_COVER_TOT_PCT)
FROM
    WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY FD
JOIN 
    MARKETING.MAILERS.DETROIT_ZIPS DZ
ON
    FD.POSTAL_CODE = DZ.POSTAL_CODE
GROUP BY
    FD.DATE_VALID_STD
ORDER BY
    AVG(FD.AVG_CLOUD_COVER_TOT_PCT);



-- 


