--- 🎯 Camilla's GeoSpatial Data (Part 1)
-- 🎯 Put Your Snowflake Skills to Work!
CREATE DATABASE MELS_SMOOTHIE_CHALLENGE_DB;
CREATE SCHEMA MELS_SMOOTHIE_CHALLENGE_DB.TRAILS;
DROP SCHEMA MELS_SMOOTHIE_CHALLENGE_DB.PUBLIC;
CREATE OR REPLACE STAGE MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.TRAILS_GEOJSON
    DIRECTORY = (ENABLE = TRUE);
CREATE OR REPLACE STAGE MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.TRAILS_PARQUET
    DIRECTORY = (ENABLE = TRUE);

-- 🎯 Load Your New Stages (geoJSON_files.zip) (cherry_creek_trail.parquet)



--- 🎯 Camilla's GeoSpatial Data (Part 2)
-- 🥋 Create a Very Basic JSON File Format
CREATE OR REPLACE FILE FORMAT MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.FF_JSON
    TYPE = JSON;

-- 🎯 Create a Very Basic Parquet File Format
CREATE OR REPLACE FILE FORMAT MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.FF_PARQUET
    TYPE = PARQUET;

-- 🥋 Query Your TRAILS_GEOJSON Stage!
SELECT * 
FROM @MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.TRAILS_GEOJSON/
(FILE_FORMAT => MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.FF_JSON);

-- 🎯 Query Your TRAILS_PARQUET Stage!
SELECT * 
FROM @MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.TRAILS_PARQUET/
(FILE_FORMAT => MELS_SMOOTHIE_CHALLENGE_DB.TRAILS.FF_PARQUET);
