-- Show all Schemas of a Database
SELECT * 
FROM GARDEN_PLANTS.INFORMATION_SCHEMA.SCHEMATA;

-- Checking for Schemas by Name
SELECT * 
FROM GARDEN_PLANTS.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('FLOWERS', 'FRUITS', 'VEGGIES');

-- Counting the Number of Correctly Named Schemas
SELECT  COUNT(*) AS SCHEMAS_FOUND, 
        '3' AS SCHEMAS_EXPECTED
FROM    GARDEN_PLANTS.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('FLOWERS', 'FRUITS', 'VEGGIES');